### ISSUE TITLE
Complexity measurement documentation

### ISSUE THREAD

**Issue by eliu1217** [eliu1217/assignment4-albumentations#2]
Document the complexity measurement done by hand and answer the questions in Assignment 3 PDF.

**Comment by danielwis** [comment]
I've written the section on Complexity measurement now, except for some of the individual contributions (i.e. own answers) left. These individual contributions are required for answering the following two questions:
- What is the purpose of these functions?
- Is the documentation of the function clear about the different possible outcomes induced by different branches taken?

I will structure the rest of the document into parts according to the assignment and create issues on here for each one, to make progress easier to track.

**Comment by danielwis** [comment]
Everyone needs to write about 2 functions each. We should close this once that's done.
